### ISSUE TITLE
Add Instructions for Joining Leaderboard

### ISSUE THREAD

**Issue by kacollins** [freecodecampnorman/freecodecampnorman.github.io#43]
Add instructions to [Leaderboard](https://fccnorman.com/leaderboard) for how to add yourself to the list.

**Comment by chris-tse** [comment]
Great idea! I believe that it would be better to put the instructions on a separate page with a link to it from the main page so that the actual leaderboard isn't cluttered up. I will leave instructions below for anyone who would like to work on this.

To do this in Gatsby, in the `pages` directory, create a folder called `leaderboard` and move the current `leaderboard.js` inside it and rename it to `index.js`, then add another page for the instructions in that folder. It might look something like this:

```
.
└── src
    └── pages
        └── leaderboard
            └── index.js
            └── instructions.js
        └── 404.js
        └── blog.js
        └── ...
```

This will make it so that `/leaderboard` is the original leaderboard and `/leaderboard/instructions` will be the new page with instructions.

**Comment by kacollins** [comment]
@OBUAdam is working on this! He might put the instructions on the leaderboard for now and then move it later (in a separate PR for Hacktoberfest haha).
